format = """
$username\
[](bg:#9C9C9C fg:#7E7E7E bold)\
$directory\
[](bg:#3cb371 fg:#9C9C9C bold)\
$git_branch\
[](bg:#00008b fg:#3cb371 bold)\
$git_status\
[](bg:#ff0371 fg:#00008b  bold)\
$time\
[ ](fg:#ff0371)\
"""
command_timeout = 5000

add_newline = true

[username]
show_always = true
style_user = "bg:#7E7E7E fg:#000000 bold"
style_root = "bg:#7E7E7E fg:#000000 bold"
format = ' [ $user]($style)'

[directory]
style = "bg:#9C9C9C fg:#000000 bold"
format = "[ $path ]($style)"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#3cb371 fg:#000000 bold"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#00008b  fg:#000000 bold"
format = '[ $all_status$ahead_behind ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#ff0371 fg:#000000 bold"
format = '[ $time ]($style)'

