format = """
[░▒▓](#a3aed2)\
[  ](bg:#9C9C9C fg:#000000)\
[](bg:#7E7E7E fg:#9C9C9C)\
$directory\
[](fg:#7E7E7E bg:#3cb371)\
$git_branch\
[](fg:#3cb371 bg:#00008b)\
$git_status\
[](fg:#00008b bg:#ff0371)\
$time\
[ ](fg:#ff0371)\
\n$character"""

[directory]
style = "fg:#000000 bg:#7E7E7E bold"
format = "[ $path ]($style)"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "fg:#000000 bg:#3cb371 bold "
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#000000 bg:#00008b bold"
format = '[( $all_status$ahead_behind )]($style)'

[time]
disabled = false
time_format = "%R" 
style = "fg:#000000 bg:#ff0371 bold"
format = '[ $time ]($style)'
